export const TableData = [
    {
        id: 1,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 2,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 3,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 4,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 5,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 6,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 7,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 8,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 9,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
    {
        id: 10,
        name: 'Tulasi Joshua',
        gender: 'Male',
        votes: 454,
        date: '21-10-2023',
    },
]